version: '3'
services:
  go:
    image: ai-interview-prod-image
    container_name: ai-interview-prod-container
    build:
      context: .
      dockerfile: container/golang/Dockerfile.Prod
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env.prod
    ports:
      - ${GOLANG_PORT}
      - ${AIR_TOML_PORT}
